spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/etc_management?characterEncoding=utf-8&useSSL=false&autoReconnect=true
    username: root
    password: root
server:
  port: 10010
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.internship.ds.model